[package]
name = "lexa-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
lexa-parsers = { path = "../parsers" }
lexa-rules = { path = "../rules" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tree-sitter = "0.20"
wasm-bindgen = "0.2"
